services:
    database:
        image: postgres:18
        container_name: store-builder-postgres
        restart: always

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: store-builder
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
    
    redis:
        image: redis:7-alpine
        container_name: store-builder-redis
        restart: always
        ports:
            - "6379:6379"

volumes:
    postgres_data:
