services:
    database:
        image: postgres:18
        container_name: store-builder-postgres
        restart: always

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: store-builder
        ports:
            - "5435:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
